version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Gradle Test
          command: gradle test
      - run:
          name: Gradle Build Jar
          command: gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/libs
          destination: prefix