version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The First Step
          command: gradle test